apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    name: quarkus-jpa-api-native
  name: quarkus-jpa-api-native-deploy
spec:
  replicas: 1
  selector:
    matchLabels:
      name: quarkus-jpa-api-native
  strategy: {}
  template:
    metadata:
      labels:
        name: quarkus-jpa-api-native
    spec:
      containers:
      - image: naveenkendyala/quarkus-jpa-api-native:0.0.31
        name: quarkus-jpa-api-native
        envFrom:
        - configMapRef:
            name: quarkus-jpa-api-native-cm
        - secretRef:
            name: quarkus-jpa-api-native-secret
        ports:
        - containerPort: 8090
        resources:
          requests:
            memory: "100Mi"
            cpu: "100m"
          limits:
            memory: "128Mi"
            cpu: "300m"
        livenessProbe:
          httpGet:
              port: 8090
              path: /applive
          initialDelaySeconds: 5
          periodSeconds: 10
          timeoutSeconds: 2          
        readinessProbe:
          httpGet:
            path: /appready
            port: 8090
          initialDelaySeconds: 5
          periodSeconds: 10
status: {}
