apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: quarkus-jpa-api-native-hpa
spec:
  maxReplicas: 10
  minReplicas: 1
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: quarkus-jpa-api-native-deploy
  targetCPUUtilizationPercentage: 50
