apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    run: quarkus-jpa-api-jvm
  name: quarkus-jpa-api-jvm-deploy
spec:
  replicas: 1
  selector:
    matchLabels:
      run: quarkus-jpa-api-jvm
  strategy: {}
  template:
    metadata:
      labels:
        run: quarkus-jpa-api-jvm
    spec:
      containers:
      - image: naveenkendyala/quarkus-jpa-api-jvm:0.0.21
        name: quarkus-jpa-api-jvm
        resources:
          limits:
            cpu: 100m
            memory: 150Mi
          requests:
            cpu: 100m
            memory: 150Mi
status: {}
