apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    name: quarkus-jpa-api-jvm
  name: quarkus-jpa-api-jvm-deploy
spec:
  replicas: 1
  selector:
    matchLabels:
      name: quarkus-jpa-api-jvm
  strategy: {}
  template:
    metadata:
      labels:
        name: quarkus-jpa-api-jvm
    spec:
      containers:
      - image: naveenkendyala/quarkus-jpa-api-jvm:0.0.22
        name: quarkus-jpa-api-jvm
        ports:
        - containerPort: 8090
        envFrom:
        - configMapRef:
            name: quarkus-jpa-api-jvm-cm
        - secretRef:
            name: quarkus-jpa-api-jvm-secret
        resources:
          limits:
            cpu: "50m"
            memory: "200Mi"
          requests:
            cpu: "50m"
            memory: "200Mi"
status: {}
