apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    name: quarkus-jpa-api-jvm
  name: quarkus-jpa-api-jvm-deploy
spec:
  replicas: 1
  selector:
    matchLabels:
      name: quarkus-jpa-api-jvm
  strategy: {}
  template:
    metadata:
      labels:
        name: quarkus-jpa-api-jvm
    spec:
      containers:
      - image: naveenkendyala/quarkus-jpa-api-jvm:0.0.16
        name: quarkus-jpa-api-jvm
        envFrom:
        - configMapRef:
            name: quarkus-jpa-api-jvm-cm
        - secretRef:
            name: quarkus-jpa-api-jvm-secret        
        ports:
        - containerPort: 8090
        resources:
          limits:
            cpu: 100m
            memory: 150Mi
          requests:
            cpu: 100m
            memory: 150Mi
status: {}
