apiVersion: autoscaling/v2beta2
kind: HorizontalPodAutoscaler
metadata:
  name: quarkus-jpa-api-jvm-hpa
spec:
  maxReplicas: 10
  minReplicas: 1
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: quarkus-jpa-api-jvm-deploy
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 50